### ISSUE TITLE
NoSuchMethodError pre API 21

### ISSUE THREAD

**Issue by twyatt** [VictorAlbertos/DeviceAnimationTestRule#4]
First off, thanks for your effort packaging up this test rule!

Unfortunately, I ran into problems pre API 21:

The library's [build.gradle](https://github.com/VictorAlbertos/DeviceAnimationTestRule/blob/master/device-animation-test-rule/build.gradle) (and test-sample module) have `minSdkVersion` set to 16 but the [test-sample](https://github.com/VictorAlbertos/DeviceAnimationTestRule/tree/master/test-sample) module crashes pre API 21.

## API 16 device

```
I/TestRunner: ----- begin exception -----
I/TestRunner: java.lang.NoSuchMethodError: android.app.Instrumentation.getUiAutomation
                  at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:105)
                  at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:269)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule.disableAnimations(DeviceAnimationTestRule.java:59)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule.access$000(DeviceAnimationTestRule.java:37)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule$1.evaluate(DeviceAnimationTestRule.java:45)
                  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                  at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                  at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
I/TestRunner: ----- end exception -----
```

_[Instrumentation.html#getUiAutomation()](https://developer.android.com/reference/android/app/Instrumentation.html#getUiAutomation()) was added API 18._

## API 18 device
```
I/TestRunner: ----- begin exception -----
I/TestRunner: java.lang.NoSuchMethodError: android.app.UiAutomation.executeShellCommand
                  at android.support.test.uiautomator.UiDevice.executeShellCommand(UiDevice.java:1060)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule.disableAnimations(DeviceAnimationTestRule.java:60)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule.access$000(DeviceAnimationTestRule.java:37)
                  at io.victoralbertos.device_animation_test_rule.DeviceAnimationTestRule$1.evaluate(DeviceAnimationTestRule.java:45)
                  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runners.Suite.runChild(Suite.java:128)
                  at org.junit.runners.Suite.runChild(Suite.java:27)
                  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                  at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                  at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
I/TestRunner: ----- end exception -----
```

_[UiAutomation.html#executeShellCommand(String)](https://developer.android.com/reference/android/app/UiAutomation.html#executeShellCommand(java.lang.String)) was added API 21._

**Comment by VictorAlbertos** [comment]
Thanks @twyatt for your feedback :)

The problem is that I do not know what would be the best approach to deal with this limitation. 

Because this library is meant to be used only for integration testing, so, I think that targeting to api 21 would be more a burden that nothing else. Because doing that, the user of this library is going to need to override the min sdk set by this library ad hoc. Because no one is going to set 21 as the min target xD. But, this requirement is only for the device in which the test are going to be run.   

So, what do you think? Any better ideas?

Thanks!

**Comment by johnjohndoe** [comment]
@twyatt In case you did not see @VictorAlbertos' post on [how to bypass the minSdkVersion limitation](https://github.com/VictorAlbertos/DeviceAnimationTestRule/pull/3#issuecomment-262366754).

**Comment by twyatt** [comment]
@VictorAlbertos, from what I can find ([Disabling Animations in Espresso for Android Testing](https://product.reverb.com/disabling-animations-in-espresso-for-android-testing-de17f7cf236f#.tw48xltw1) and [Gist: Disable animations for Espresso tests](https://gist.github.com/xrigau/11284124)), it seems that issuing `adb` commands would be necessary for disabling animations pre API 21? Which is probably outside the scope of what you intended for this project?

That being said, perhaps it would be helpful to have the API limitation documented? When I stumbled on this gem I assumed it worked down to API 16 (based on the build.gradle in the sample app).

**Comment by VictorAlbertos** [comment]
@johnjohndoe I thin this is the exactly opposite scenario ;)

@twyatt Yes. I think I'm going to document the issue. Thanks for your feedback!

**Comment by johnjohndoe** [comment]
@VictorAlbertos Maybe, I misunderstand the issue.
@twyatt For completeness - this article on "[Setting animation scale for Android UI tests](http://www.thedroidsonroids.com/blog/setting-animation-scale-for-android-ui-tests/)" might interest you.

**Comment by twyatt** [comment]
@johnjohndoe Thanks for linking the article!

Although I'm not sure what is going wrong for me, as neither the method discussed in the article (nor the [Gradle plugin mentioned](https://plugins.gradle.org/plugin/pl.droidsonroids.animation-disabler)) worked for me. 😢 

Even tried issuing `adb` commands (as mentioned in [tasomaniac's comment](https://gist.github.com/xrigau/11284124#gistcomment-1662145)) [without success](https://gist.github.com/xrigau/11284124#gistcomment-1962018).

So, I still have yet to find a reliable means of disabling animations for testing (that is compatible pre API 21) without having to [manually update settings](https://google.github.io/android-testing-support-library/docs/espresso/setup/#setup-your-test-environment) on every emulator.

**Comment by tir38** [comment]
May I suggest some sort of fail safe that checks API level before executing this code? Right now, if I run tests on API < 21 i'll just see a crash with no indication of why. It would be nice if I either got a log warning "Hey we were unable to turn off animations", or at the very least just do nothing (i.e. keep animations turned on)

**Comment by VictorAlbertos** [comment]
@tir38 do you care to submit a PR? Thanks.
